### ISSUE TITLE
[Bug] missing dependency js-beautify

### ISSUE THREAD

**Issue by semicolin** [skoropadas/ng-doc#22]
### Is this a regression?

I don't know

### Description

I added ng-doc to a new Angular app using `ng add @ng-doc/add` and then tried to build it with `ng build`. I got an error about `js-beautify` dependency. I had to manually install this dependency to resolve the error.

### Please provide the exception or error you saw

```true
./node_modules/@ng-doc/app/fesm2020/ng-doc-app-helpers-format-html.mjs:11:14-59 - Error: Module not found: Error: Can't resolve 'js-beautify/js/lib/beautify-html.js' in 'node_modules/@ng-doc/app/fesm2020'
```

### OS

Unix (Linux, macOS, etc.)

### Browser

Chrome

### Node version

18.12.1

**Comment by skoropadas** [comment]
Yap, my bad, forgot to add it to the dependencies, I will fix it and release new version tomorrow, as workaround you can install this package manually, and remove later with the update
