### ISSUE TITLE
[Feature] Allow customizing the header levels for auto-generated anchor links

### ISSUE THREAD

**Issue by R-Bower** [skoropadas/ng-doc#27]
### Description

Currently, every anchor element (`h1-h6`) generates an anchor link.  

### Proposed solution

I'd like to be able to customize these levels (e.g. only generate links for `h1, h2, h3` elements)

### Alternatives considered

None

**Comment by skoropadas** [comment]
Ok no problem, I will add it with a new global config file

**Comment by skoropadas** [comment]
Hey, I've added a new property to the new configuration file, when this ticket will be released you should be able to configure headings like on the example [here](https://github.com/skoropadas/ng-doc/blob/10aaa20525dea2ebd56f72ac9e670f55f01c981f/apps/ng-doc/ng-doc.config.ts#L29)
