### ISSUE TITLE
[Bug] Global CSS styles leak into component demos

### ISSUE THREAD

**Issue by semicolin** [skoropadas/ng-doc#28]
### Is this a regression?

I don't know

### Description

Component demos have extra CSS styles that are not there when rendered outside of ng-doc. For example, create a demo with a `<table>` element and note the margin that is coming from global.css.

### Please provide the exception or error you saw

```true
N/A
```

### OS

Unix (Linux, macOS, etc.)

### Browser

Chrome

### Node version

18.12.1

### Anything else?

![image](https://user-images.githubusercontent.com/2105775/223226137-5c1fa9e1-fe81-4fe8-887e-b2cd5aa8cbbb.png)

**Comment by R-Bower** [comment]
I've noticed this as well with heading, paragraph, and list elements.

**Comment by skoropadas** [comment]
Good catch guys! I will start fixing it asap, I definitely should use classes when converting markdown to HTML and not use global styles

**Comment by skoropadas** [comment]
Ok, I've decided to try rendering the demo inside a component with `encapsulation: ViewEncapsulation.ShadowDom`. This will prevent global styles from interfering and make the demo more independent of the environment. In any case, if you encounter other errors related to global styles, just let me know, and I might return to the option of adding classes.

**Comment by semicolin** [comment]
It looks like this change completely broke my chart.js component demos. I'm not sure exactly why, but I can write a repro if you want.

**Comment by skoropadas** [comment]
No, I think I'll rollback these changes, it looks like it's impossible to use shadow-dom due to external libraries that can be used in components, so they will never be displayed correctly

**Comment by skoropadas** [comment]
Now it should work fine, global styles that I used now apply only when a certain class is present, so default elements should have default values. Anyway, tell me if I missed anything

**Comment by semicolin** [comment]
Looks good. Thanks!
