### ISSUE TITLE
Examples or visual references? [Docs] 

### ISSUE THREAD

**Issue by dgrbrady** [skoropadas/ng-doc#32]
### Description

Super interested in this library, but it's not clear to me what kind of documentation is generated by using `ng-doc`. Are there any screenshots available of what the end result looks like after setting everything up?

**Comment by skoropadas** [comment]
Sure, documentation for NgDoc was created via NgDoc, so you can do the same using this library, write guides, create demos and automatically generate documentation for your API based on your code comments and it will look like this - https://ng-doc.com/

**Comment by skoropadas** [comment]
I'm currently working on the landing page that will demonstrate the process of creating documentation, some advantages, features etc.

Also here is the video demonstration of writing guides that you can check - http://assets.ng-doc.com/ng-doc-in-action-landscape.mp4
And you can play with it on a stackblitz - https://stackblitz.com/edit/node-pw2tyk?file=src%2Fapp%2Fbutton%2Fbutton.component.ts,src%2Fapp%2Fdocs%2Fbutton%2Findex.md

**Comment by skoropadas** [comment]
I am closing this ticket, because now a [landing page](https://ng-doc.com/) is available on which you can see an example of use.
