### ISSUE TITLE
[Bug] New demo code previews are unavailable until the application is restarted.

### ISSUE THREAD

**Issue by R-Bower** [skoropadas/ng-doc#33]
### Is this a regression?

I don't know

### Description

When adding a new demo component to an ng-doc page, the HTML/TypeScript code previews are unavailable until I restart the docs application.  The code hide/show button is available, but it doesn't do anything when clicked.

### OS

Unix (Linux, macOS, etc.)

### Browser

Chrome

### Node version

18+

**Comment by skoropadas** [comment]
Does it happen with the latest version of the library?

**Comment by skoropadas** [comment]
Found a problem, there is something wrong with `minimatch` library that I use inside the builder 🤨 tomorrow I will check what is wrong with it and why it is not working properly
