### ISSUE TITLE
[Feature] Conditionally remove docs page from sidebar

### ISSUE THREAD

**Issue by R-Bower** [skoropadas/ng-doc#35]
### Description

There are situations where I want to keep a docs page on the site, but prevent it from appearing in the sidebar.  I'd like this configuration to live at the `ng-doc.page.ts` level.  

### Proposed solution

Add `sidebar` boolean field to `NgDocPage` interface.  When set to `false`, remove element from sidebar.

### Alternatives considered

I've implemented my own sidebar which filters `context.navigation`, but an official integration would be nice.

**Comment by skoropadas** [comment]
Do you need this page in the production build? I'm asking because maybe you just want to create a development page to develop some components on it

**Comment by R-Bower** [comment]
Yes, still need the page in the production build.  Example: page link is available somewhere on the site, but not from the sidebar.

**Comment by R-Bower** [comment]
For pages that I don't want to show in the sidebar, but still want to render with ng-doc.  

Nextra provides a way to do this:
https://nextra.site/docs/docs-theme/page-configuration#hidden-routes

**Comment by skoropadas** [comment]
Yes, I see and understand what you want, I just don't understand the use cases of this, but ok I'll add it to the next release

**Comment by R-Bower** [comment]
There are situations where I want a page but don't want it to crowd up the
sidebar.  I'm not sure how to explain it more than that.

**Comment by skoropadas** [comment]
No problem, it's not difficult to add I just wanted to understand all possible use cases of this feature to implement it correctly, I will release it with code blocks improvements

**Comment by skoropadas** [comment]
I decided to release this feature today because I need more time to finish the improvements for the code blocks, in addition I want to add several other features in the next release, improve the search that you requested earlier, a new version of the demo, and most likely the option demo that you asked in one of the tickets, in general the next release will be much more bigger than usual and I need more time to prepare it
