### ISSUE TITLE
[Bug] default param value displayed as [object Object]

### ISSUE THREAD

**Issue by semicolin** [skoropadas/ng-doc#40]
### Is this a regression?

Yes

### Description

Default values for method parameters are displayed as `[object Object]` in the API page presentation.
The signature for this method is:
```
  enable(id: string, enabled = true)
```
![image](https://user-images.githubusercontent.com/2105775/229651380-3e4f8961-2d5b-4903-ae88-31835fc025f9.png)

### OS

Unix (Linux, macOS, etc.)

### Browser

Chrome

### Node version

18.12.1

**Comment by skoropadas** [comment]
Hey, thanks for the ticket! Have you tried to install the latest version 15.10.4? I noticed that some API types were displayed incorrectly, so I fixed some errors and added tests for the function that is responsible for this

**Comment by skoropadas** [comment]
Okay, no matter, I see that this is reproducible only for presentations, I will fix it asap!

**Comment by skoropadas** [comment]
I fixed this bug and several others that I found while writing tests, so now it should work, thanks for the issue again!

**Comment by semicolin** [comment]
Looks good. Thanks for the quick fix!
