### ISSUE TITLE
Search bar shows "Unknown"

### ISSUE THREAD

**Issue by R-Bower** [skoropadas/ng-doc#6]
**Describe the bug**
"Unknown" text is appearing in ng-doc searchbar.

**To Reproduce**
1. Go to https://ng-doc.com/customization/themes
2. Type "getting started" in the search bar
3. See error

**Expected behavior**
"Unknown" shouldn't appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/11933208/217378732-5b8561f3-1407-4902-879a-edfe7ff226be.png)

**Comment by skoropadas** [comment]
Hey, thanks for the bug report! It will be fixed in the next release :)
