### ISSUE TITLE
Build hangs

### ISSUE THREAD

**Issue by R-Bower** [skoropadas/ng-doc#7]
**Describe the bug**
Using the `@ng-doc/builder:browser` builder, `ng build` completes successfully but doesn't exit.  

**To Reproduce**
1. Start a new angular app.
2. Follow the installation instructions for adding @ng-doc
3. Try `ng build`.
4. Observe as the build emits a completion message, but hangs:

`Build at: 2023-02-09T00:51:37.798Z - Hash: 54d6279d114249fc - Time: 9947ms`

I'm also using `pnpm`.  Not sure if that matters.

**Expected behavior**
The CLI exits after build.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 12.5.1

**Comment by skoropadas** [comment]
Thanks for the report, will fix it asap!

**Comment by R-Bower** [comment]
Thank you for the quick fix!  I'm honestly surprised that this library isn't more popular.  It's very cool.

**Comment by skoropadas** [comment]
@R-Bower you are welcome, and thanks! I just released it, and at the moment I'm writing a guide on medium to advertise it a bit 😀
