### ISSUE TITLE
TypeScript types don't match docs

### ISSUE THREAD

**Issue by R-Bower** [skoropadas/ng-doc#9]
**Describe the bug**
The docs recommend TypeScript imports for pages as follows:

```typescript
import {NgDocPage} from '@ng-doc/builder';

export const MyAwesomePage: NgDocPage = {
    title: 'MyAwesomePage',
    mdFile: './index.md',
};

export default MyAwesomePage;
```

The types aren't resolved as expected.  Instead, my IDE detected the types from the `@ng-doc/core` package.

**To Reproduce**
1. Use the default installation on a blank app.
2. Try to import the TypeScript types as done in the docs.
3. Notice as the types aren't resolved properly.

**Expected behavior**
The types are resolved as documented.

**Comment by skoropadas** [comment]
True, that's my bad. Before release, I moved entities classes to `@ng-doc/core` library but forgot to update docs, thank you for the report! 😌
